version: 2.1
orbs:
  docker: circleci/docker@0.5.20
  slack: circleci/slack@3.4.2

# Parameters are available to all elements of config.yml, those are accessible using `pipeline.parameters.PARAMETER`
parameters:
  slack_channel_regular:
    type: string
    default: "#cci-jahia-ui-root"
  slack_channel_urgent:
    type: string
    default: "#cci-jahia-ui-root"
  slack_mention_regular:
    type: string
    default: "parveer,aademi"
  slack_mention_urgent:
    type: string
    default: "channel"
  auditci_level:
    type: string
    default: "high"
  javascript_directory:
    type: string
    default: "./"

aliases:
  - &notify_slack_failure_regular
    slack/status:
      channel: << pipeline.parameters.slack_channel_regular >>
      fail_only: true
      include_project_field: true
      include_visit_job_action: true
      mentions: << pipeline.parameters.slack_mention_regular >>
  - &notify_slack_failure_urgent
    slack/status:
      channel: << pipeline.parameters.slack_channel_urgent >>
      fail_only: true
      include_project_field: true
      include_visit_job_action: true
      mentions: << pipeline.parameters.slack_mention_urgent >>

references:
  workdir: &workdir
    working_directory: ~/source

  persist-workspace: &persist-workspace
    persist_to_workspace:
      root: ~/source
      paths:
        - .

  attach-workspace: &attach-workspace
    attach_workspace:
      at: .

jobs:
  # Checkout and Initializes the testing framework
  initialize:
    <<: *workdir
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-npm-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: |
            yarn
      - save_cache:
          key: v2-npm-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - *persist-workspace
      - *notify_slack_failure_regular

  # Lint the project
  # This action should run in parrallel, failed linting should trigger an error but should not stop execution of the tests
  lint:
    docker:
      - image: circleci/node:12
    working_directory: ~/source/
    steps:
      - *attach-workspace
      - run:
          name: Yarn lint
          command: |
            yarn run lint
      - *notify_slack_failure_regular

  security:
    <<: *workdir
    docker:
      - image: circleci/node:12
    steps:
      - *attach-workspace
      - run:
          name: Install dependencies
          command: sudo npm install -g audit-ci
      - run:
          name: Run Audit-ci javascript app
          command: |
            cd << pipeline.parameters.javascript_directory >>
            audit-ci --<< pipeline.parameters.auditci_level >>
      - *notify_slack_failure_regular

  # The initialize clone and yarn install
  build:
    <<: *workdir
    docker: # run the steps with Docker
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - *attach-workspace
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: mvn -s .circleci/.circleci.settings.xml clean install
      # Built module is stored in: /home/circleci/source/repo/repo/api/target/augmented-search-1.0.1-SNAPSHOT.jar
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run:
          name: Prepare artifacts
          command: |
            mkdir /tmp/artifacts/
            cp /home/circleci/source/target/*.jar /tmp/artifacts/
      - store_artifacts:
          path: /tmp/artifacts/
      - *persist-workspace

  # This job publish the artifact to nexus by calling the deploy command
  # It is only executed when merging into master (after successful PR execution)
  publish:
    <<: *workdir
    docker:
      - image: cimg/openjdk:8.0.275
    steps:
      - *attach-workspace
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: 
          name: Deploy the artifact to Nexus
          command: |
            mvn -s .circleci/.circleci.settings.xml clean install deploy
          no_output_timeout: 30m

  # Run unit tests
  # This action should run in parrallel, failed linting should trigger an error but should not stop execution of the tests
  unit_tests:
    <<: *workdir
    docker:
      - image: circleci/node:12-browsers
    steps:
      - *attach-workspace
      - run:
          name: Running unit tests with jest
          command: |
            yarn run tests:unit --ci
      - *notify_slack_failure_regular

workflows:
  version: 2
  on-code-change:
    jobs:
      - initialize
      - lint:
          requires:
            - initialize
      - security:
          requires:
            - initialize
      - unit_tests:
          requires:
            - initialize
      - build:
          requires:
            - initialize
      - publish:
          context: QA_ENVIRONMENT
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - /[0-9]_x/
                - /[0-9]_[0-9]_x/
