const constants = {
    TEST_URL: 'TEST_URL',
    IGNORE_TESTS: 'IGNORE_TESTS',
    SNAPSHOTS_DIR: 'SNAPSHOTS_DIR',
    JAHIA_USERNAME: 'JAHIA_USERNAME',
    JAHIA_PASSWORD: 'JAHIA_PASSWORD',
    TESTRAIL_USERNAME: 'TESTRAIL_USERNAME',
    TESTRAIL_PASSWORD: 'TESTRAIL_PASSWORD',
    TESTRAIL_URL: 'TESTRAIL_URL',
    TESTRAIL_MILESTONE: 'TESTRAIL_MILESTONE',
    TESTRAIL_RUNDESCRIPTION: 'TESTRAIL_RUNDESCRIPTION'
};

module.exports = constants;
